$(document).ready(function(){
					$("#simples-text").hide();
					$("#exclusivo-text").hide();
					$("#hospedagem-text").hide();
					$("#manutencao-text").hide();
					$("#personalizado-text").hide();
					
    				$(".simples").click(function(){
        				$("#simples-text").slideToggle();
    					$("#exclusivo-text").hide();
						$("#hospedagem-text").hide();
						$("#manutencao-text").hide();
						$("#personalizado-text").hide();
    				});
    				$(".exclusivo").click(function(){
        				$("#exclusivo-text").slideToggle();
        				$("#simples-text").hide();
						$("#hospedagem-text").hide();
						$("#manutencao-text").hide();
						$("#personalizado-text").hide();
    				});
    				$(".hospedagem").click(function(){
        				$("#hospedagem-text").slideToggle();
        				$("#exclusivo-text").hide();
						$("#simples-text").hide();
						$("#manutencao-text").hide();
						$("#personalizado-text").hide();
    				});
    				$(".manutencao").click(function(){
        				$("#manutencao-text").slideToggle();
        				$("#exclusivo-text").hide();
						$("#hospedagem-text").hide();
						$("#simples-text").hide();
						$("#personalizado-text").hide();
    				});
    				$(".personalizado").click(function(){
        				$("#personalizado-text").slideToggle();
        				$("#manutencao-text").hide();
        				$("#exclusivo-text").hide();
						$("#hospedagem-text").hide();
						$("#simples-text").hide();
    				});
				});